#include <SFML/Audio.hpp>
#include <cmath>
#include <ctime>
#include <SFML/Graphics.hpp>
#include <sstream>
#include <string>
using namespace std;
using namespace sf;
int main (){
	int sisi=500;
	float percepat=0.25, kecepatanx=0,kecepatany=0,
	gantix,gantiy,
	ganti1x,ganti1y,
	ganti2x,ganti2y,
	ganti3x,ganti3y,
	ganti4x,ganti4y,
	ganti5x,ganti5y,
	ganti6x,ganti6y,
	ganti7x,ganti7y;
	bool dapat1=false, dapat2=false, dapat3=false, dapat4=false, 
	dapat5=false, dapat6=false, dapat7=false;
	RenderWindow ahhh(VideoMode(sisi, sisi),"BOSEN");
	ahhh.setFramerateLimit(60);
	
	Font biasa;
	biasa.loadFromFile("tes.ttf");
	Clock waktu;
	string ena="menu";
	ostringstream konvert, sisaan;
	int hitung=30, w, sisa=0, d1=1, d2=1, d3=1, d4=1, d5=1, d6=1, d7=1;
	float ukuran=25, x1=5,x2=5,x3=5,x4=5,x5=5,x6=5,x7=5;
	Text waktunya, sisanya;
	waktunya.setFont(biasa);
	waktunya.setPosition(0,0);
	sisanya.setFont(biasa);
	sisanya.setPosition(0,450);

	Music bgmmain, bgmseram, bgmsedih, bgmserius, bgmbiasa, bgmgagal, bgmfinal;
	bgmseram.openFromFile("suara/bgm/seram.ogg");
	bgmmain.openFromFile("suara/bgm/main.ogg");
	bgmsedih.openFromFile("suara/bgm/sedih.ogg");
	bgmserius.openFromFile("suara/bgm/serius.ogg");
	bgmbiasa.openFromFile("suara/bgm/biasa.ogg");
	bgmgagal.openFromFile("suara/bgm/gagal.ogg");
	bgmfinal.openFromFile("suara/bgm/final.ogg");
	bool bgmseramy=false, bgmmainy=false, bgmsedihy=false, bgmseriusy=false,
	bgmbiasay=false, bgmgagaly=false, bgmfinaly=false;
	bgmseram.setLoop(true);
	bgmmain.setLoop(true);
	bgmsedih.setLoop(true);
	bgmserius.setLoop(true);
	
	Texture awalx, level1x, zerox, overx;
	awalx.loadFromFile("gambar/awal.jpg");
	zerox.loadFromFile("gambar/0.jpg");
	level1x.loadFromFile("gambar/1.jpg");
	overx.loadFromFile("gambar/over.jpg");
	Sprite awal(awalx), level1(level1x), zero(zerox), over(overx);
	
	
	Texture c1n1x, c1n2x, c1n3x, c1n4x, c1n5x, c1n6x, c1n7x, c1n8x, c1n9x,
	c1xn1x, c1xn2x, c1xn3x, c1xn4x, c1xn5x, c1xn6x, c1xn7x, c1xn8x, c1xn9x,
	c2n1x, c2n2x, c2n3x, c2n4x, c2n5x, c2n6x, c2n7x, c2n8x, c2n9x;
	c1n1x.loadFromFile("gambar/1/1.jpg");
	c1n2x.loadFromFile("gambar/1/2.jpg");
	c1n3x.loadFromFile("gambar/1/3.jpg");
	c1n4x.loadFromFile("gambar/1/4.jpg");
	c1n5x.loadFromFile("gambar/1/5.jpg");
	c1n6x.loadFromFile("gambar/1/6.jpg");
	c1n7x.loadFromFile("gambar/1/7.jpg");
	c1n8x.loadFromFile("gambar/1/8.jpg");
	c1n9x.loadFromFile("gambar/1/9.jpg");
	c1xn1x.loadFromFile("gambar/x1/1.jpg");
	c1xn2x.loadFromFile("gambar/x1/2.jpg");
	c1xn3x.loadFromFile("gambar/x1/3.jpg");
	c1xn4x.loadFromFile("gambar/x1/4.jpg");
	c1xn5x.loadFromFile("gambar/x1/5.jpg");
	c1xn6x.loadFromFile("gambar/x1/6.jpg");
	c1xn7x.loadFromFile("gambar/x1/7.jpg");
	c1xn8x.loadFromFile("gambar/x1/8.jpg");
	c1xn9x.loadFromFile("gambar/x1/9.jpg");
	c2n1x.loadFromFile("gambar/2/1.jpg");
	c2n2x.loadFromFile("gambar/2/2.jpg");
	c2n3x.loadFromFile("gambar/2/3.jpg");
	c2n4x.loadFromFile("gambar/2/4.jpg");
	c2n5x.loadFromFile("gambar/2/5.jpg");
	c2n6x.loadFromFile("gambar/2/6.jpg");
	c2n7x.loadFromFile("gambar/2/7.jpg");
	c2n8x.loadFromFile("gambar/2/8.jpg");
	c2n9x.loadFromFile("gambar/2/9.jpg");
	Sprite c1n1(c1n1x),
	c1n2(c1n2x),
	c1n3(c1n3x),
	c1n4(c1n4x),
	c1n5(c1n5x),
	c1n6(c1n6x),
	c1n7(c1n7x),
	c1n8(c1n8x),
	c1n9(c1n9x),
	c1xn1(c1xn1x),
	c1xn2(c1xn2x),
	c1xn3(c1xn3x),
	c1xn4(c1xn4x),
	c1xn5(c1xn5x),
	c1xn6(c1xn6x),
	c1xn7(c1xn7x),
	c1xn8(c1xn8x),
	c1xn9(c1xn9x),
	c2n1(c2n1x),
	c2n2(c2n2x),
	c2n3(c2n3x),
	c2n4(c2n4x),
	c2n5(c2n5x),
	c2n6(c2n6x),
	c2n7(c2n7x),
	c2n8(c2n8x),
	c2n9(c2n9x);
	
	CircleShape pemain;
	pemain.setRadius(ukuran);
	pemain.setFillColor(Color::Green);
	pemain.setPosition(235,235);
	
	RectangleShape obat1, obat2, obat3, obat4, obat5, obat6, obat7;
	obat1.setSize(Vector2f(10,20));
	obat1.setFillColor(Color::White);
	obat2.setSize(Vector2f(10,20));
	obat2.setFillColor(Color::White);
	obat3.setSize(Vector2f(10,20));
	obat3.setFillColor(Color::White);
	obat4.setSize(Vector2f(10,20));
	obat4.setFillColor(Color::White);
	obat5.setSize(Vector2f(10,20));
	obat5.setFillColor(Color::White);
	obat6.setSize(Vector2f(10,20));
	obat6.setFillColor(Color::White);
	obat7.setSize(Vector2f(10,20));
	obat7.setFillColor(Color::White);
	
	while(ahhh.isOpen()){
		Event kuy;
		while(ahhh.pollEvent(kuy)){
			ahhh.clear();
			if (kuy.type == Event::Closed){
                ahhh.close();
                break;
            }
			if(Keyboard::isKeyPressed(Keyboard::S)){
                if((ena=="bab1n1")or(ena=="bab1n2")or(ena=="bab1n3")or(ena=="bab1n4")
			    or(ena=="bab1n5")or(ena=="bab1n6")or(ena=="bab1n7")or(ena=="bab1n8")){
				    waktu.restart();
				    ena="bab1n9";
			    }
			    if((ena=="bab1xn1")or(ena=="bab1xn2")or(ena=="bab1xn3")or(ena=="bab1xn4")or(ena=="bab1xn5")or
				(ena=="bab1xn6")or(ena=="bab1xn7")or(ena=="bab1xn8")or(ena=="bab1xn9")){
			    	waktu.restart();
			    	ena="over";
			    }
		    }
        }
		if(ena=="menu"){
			if(bgmmainy==false){
				bgmseram.stop();bgmseramy=false;
				bgmserius.stop();bgmseriusy=false;
				bgmsedih.stop();bgmsedihy=false;
				bgmbiasa.stop();bgmbiasay=false;
				bgmgagal.stop();bgmgagaly=false;
				bgmfinal.stop();bgmfinaly=false;
				bgmmain.play();bgmmainy=true;
			}
			ahhh.draw(awal);
			if(Keyboard::isKeyPressed(Keyboard::Space)){
				waktu.restart();
				ena="bab1n1";
			}
		}
		if(ena=="bab1n1"){
			if(bgmbiasay==false){
				bgmseram.stop();bgmseramy=false;
				bgmserius.stop();bgmseriusy=false;
				bgmsedih.stop();bgmsedihy=false;
				bgmbiasa.play();bgmbiasay=true;
				bgmgagal.stop();bgmgagaly=false;
				bgmfinal.stop();bgmfinaly=false;
				bgmmain.stop();bgmmainy=false;
			}
			w=waktu.getElapsedTime().asSeconds();
			ahhh.draw(c1n1);
			if(w>3){
				waktu.restart();
				ena="bab1n2";
			}
		}
		if(ena=="bab1n2"){
			w=waktu.getElapsedTime().asSeconds();
			ahhh.draw(c1n2);
			if(w>3){
				waktu.restart();
				ena="bab1n3";
			}
		}
		if(ena=="bab1n3"){
			if(bgmsedihy==false){
				bgmseram.stop();bgmseramy=false;
				bgmserius.stop();bgmseriusy=false;
				bgmsedih.play();bgmsedihy=true;
				bgmbiasa.stop();bgmbiasay=false;
				bgmgagal.stop();bgmgagaly=false;
				bgmfinal.stop();bgmfinaly=false;
				bgmmain.stop();bgmmainy=false;
			}
			w=waktu.getElapsedTime().asSeconds();
			ahhh.draw(c1n3);
			if(w>3){
				waktu.restart();
				ena="bab1n4";
			}
		}
		if(ena=="bab1n4"){
			w=waktu.getElapsedTime().asSeconds();
			ahhh.draw(c1n4);
			if(w>3){
				waktu.restart();
				ena="bab1n5";
			}
		}
		if(ena=="bab1n5"){
			w=waktu.getElapsedTime().asSeconds();
			ahhh.draw(c1n5);
			if(w>3){
				waktu.restart();
				ena="bab1n6";
			}
		}
		if(ena=="bab1n6"){
			w=waktu.getElapsedTime().asSeconds();
			ahhh.draw(c1n6);
			if(w>3){
				waktu.restart();
				ena="bab1n7";
			}
		}
		if(ena=="bab1n7"){
			w=waktu.getElapsedTime().asSeconds();
			ahhh.draw(c1n7);
			if(w>3){
				waktu.restart();
				ena="bab1n8";
			}
		}
		if(ena=="bab1n8"){
			w=waktu.getElapsedTime().asSeconds();
			ahhh.draw(c1n8);
			if(w>3){
				waktu.restart();
				ena="bab1n9";
			}
		}
		if(ena=="bab1n9"){
			w=waktu.getElapsedTime().asSeconds();
			ahhh.draw(c1n9);
			if(w>3){
				waktu.restart();
				x1=0;x2=0;x3=0;x4=0;x5=0;x6=0;x7=0;
			    gantix=-500;gantiy=-500;
			    ganti1x=-107;ganti1y=534;
                ganti2x=521;ganti2y=264;
	            ganti3x=103;ganti3y=0;
	            ganti4x=243;ganti4y=123;
	            ganti5x=138;ganti5y=-185;
	            ganti6x=666;ganti6y=666;
	            ganti7x=721;ganti7y=-194;
			    dapat1=false;dapat2=false;dapat3=false;
			    dapat4=false;dapat5=false;
			    dapat6=false;dapat7=false;
           		ena="level1";
           	}
		}
		if(ena=="level1"){
			if(bgmseramy==false){
				bgmseram.play();bgmseramy=true;
				bgmserius.stop();bgmseriusy=false;
				bgmsedih.stop();bgmsedihy=false;
				bgmbiasa.stop();bgmbiasay=false;
				bgmgagal.stop();bgmgagaly=false;
				bgmfinal.stop();bgmfinaly=false;
				bgmmain.stop();bgmmainy=false;
			}
			ahhh.draw(zero);
			ahhh.draw(level1);
			if(dapat1==false){
				d1=1;
    			ahhh.draw(obat1);
    		}
    		else{
    			d1=0;
			}
    		if(dapat2==false){
    			d2=1;
			    ahhh.draw(obat2);
			}
			else{
    			d2=0;
			}
			if(dapat3==false){
				d3=1;
    			ahhh.draw(obat3);
    		}
    		else{
    			d3=0;
			}
    		if(dapat4==false){
    			d4=1;
			    ahhh.draw(obat4);
		    }
		    else{
    			d4=0;
			}
		    if(dapat5==false){
		    	d5=1;
			    ahhh.draw(obat5);
			}
			else{
    			d5=0;
			}
			if(dapat6==false){
				d6=1;
    			ahhh.draw(obat6);
    		}
    		else{
    			d6=0;
			}
    		if(dapat7==false){
    			d7=1;
			    ahhh.draw(obat7);
			}
			else{
    			d7=0;
			}
			ahhh.draw(pemain);
			sisaan.str("");
			sisa=d1+d2+d3+d4+d5+d6+d7;
			sisaan<<sisa;
			sisanya.setString("OBAT TERSISA : "+sisaan.str());
			if(sisa<=0){
				waktu.restart();
				ena="bab2n1";
			}
			ahhh.draw(sisanya);
			konvert.str("");
			w=waktu.getElapsedTime().asSeconds();
			konvert<<hitung-w;
			waktunya.setString("SISA WAKTU : "+konvert.str());
			ahhh.draw(waktunya);
			if (Keyboard::isKeyPressed){
			    if((Keyboard::isKeyPressed(Keyboard::Right))or(Keyboard::isKeyPressed(Keyboard::D))) {
   					if(kecepatanx<4){
    					kecepatanx+=percepat;
	    		    }
		    	    else{
			        	kecepatanx=3;
			        }
			        if(level1.getPosition().x<=-1000){
			        	kecepatanx=0;
					}
			        gantix=level1.getPosition().x-kecepatanx;
			        ganti1x=obat1.getPosition().x-kecepatanx;
			        ganti2x=obat2.getPosition().x-kecepatanx;
			        ganti3x=obat3.getPosition().x-kecepatanx;
			        ganti4x=obat4.getPosition().x-kecepatanx;
			        ganti5x=obat5.getPosition().x-kecepatanx;
			        ganti6x=obat6.getPosition().x-kecepatanx;
			        ganti7x=obat7.getPosition().x-kecepatanx;
			    }
			    if((Keyboard::isKeyPressed(Keyboard::Left))or(Keyboard::isKeyPressed(Keyboard::A))){
   					if(kecepatanx>-4){
    					kecepatanx-=percepat;
	    		    }
		    	    else{
			        	kecepatanx=-3;
			        }
			        if(level1.getPosition().x>=0){
			        	kecepatanx=0;
					}
			        gantix=level1.getPosition().x-kecepatanx;
			        ganti1x=obat1.getPosition().x-kecepatanx;
			        ganti2x=obat2.getPosition().x-kecepatanx;
			        ganti3x=obat3.getPosition().x-kecepatanx;
			        ganti4x=obat4.getPosition().x-kecepatanx;
			        ganti5x=obat5.getPosition().x-kecepatanx;
			        ganti6x=obat6.getPosition().x-kecepatanx;
			        ganti7x=obat7.getPosition().x-kecepatanx;
			    }
			    if((Keyboard::isKeyPressed(Keyboard::Up))or(Keyboard::isKeyPressed(Keyboard::W))) {
   					if(kecepatany>-4){
    					kecepatany-=percepat;
	    		    }
		    	    else{
			        	kecepatany=-3;
			        }
			        if(level1.getPosition().y>=0){
			        	kecepatany=0;
					}
					gantiy=level1.getPosition().y-kecepatany;
					ganti1y=obat1.getPosition().y-kecepatany;
			        ganti2y=obat2.getPosition().y-kecepatany;
			        ganti3y=obat3.getPosition().y-kecepatany;
			        ganti4y=obat4.getPosition().y-kecepatany;
			        ganti5y=obat5.getPosition().y-kecepatany;
			        ganti6y=obat6.getPosition().y-kecepatany;
			        ganti7y=obat7.getPosition().y-kecepatany;
			    }
			    if((Keyboard::isKeyPressed(Keyboard::Down))or(Keyboard::isKeyPressed(Keyboard::S))) {
   					if(kecepatany<4){
    					kecepatany+=percepat;
	    		    }
		    	    else{
			        	kecepatany=3;
			        }
			        if(level1.getPosition().y<=-1000){
			        	kecepatany=0;
					}
			        gantiy=level1.getPosition().y-kecepatany;
			        ganti1y=obat1.getPosition().y-kecepatany;
			        ganti2y=obat2.getPosition().y-kecepatany;
			        ganti3y=obat3.getPosition().y-kecepatany;
			        ganti4y=obat4.getPosition().y-kecepatany;
			        ganti5y=obat5.getPosition().y-kecepatany;
			        ganti6y=obat6.getPosition().y-kecepatany;
			        ganti7y=obat7.getPosition().y-kecepatany;
			    }
			}
			else{
				ganti1x=obat1.getPosition().x;
				ganti1y=obat1.getPosition().y;
				ganti2x=obat2.getPosition().x;
				ganti2y=obat2.getPosition().y;
				ganti3x=obat3.getPosition().x;
				ganti3y=obat3.getPosition().y;
				ganti4x=obat4.getPosition().x;
				ganti4y=obat4.getPosition().y;
				ganti5x=obat5.getPosition().x;
				ganti5y=obat5.getPosition().y;
				ganti6x=obat6.getPosition().x;
				ganti6y=obat6.getPosition().y;
				ganti7x=obat7.getPosition().x;
				ganti7y=obat7.getPosition().y;
				gantix=level1.getPosition().x;
				gantiy=level1.getPosition().y;
			}
			level1.setPosition(gantix,gantiy);
			obat1.setPosition(ganti1x,ganti1y);
			obat2.setPosition(ganti2x,ganti2y);
			obat3.setPosition(ganti3x,ganti3y);
			obat4.setPosition(ganti4x,ganti4y);
			obat5.setPosition(ganti5x,ganti5y);
			obat6.setPosition(ganti6x,ganti6y);
			obat7.setPosition(ganti7x,ganti7y);
			if(pemain.getGlobalBounds().intersects(obat1.getGlobalBounds())){
				dapat1=true;
				x1=5;
			}
			if(pemain.getGlobalBounds().intersects(obat2.getGlobalBounds())){
				dapat2=true;
				x2=5;
			}
			if(pemain.getGlobalBounds().intersects(obat3.getGlobalBounds())){
				dapat3=true;
				x3=5;
			}
			if(pemain.getGlobalBounds().intersects(obat4.getGlobalBounds())){
				dapat4=true;
				x4=5;
			}
			if(pemain.getGlobalBounds().intersects(obat5.getGlobalBounds())){
				dapat5=true;
				x5=5;
			}
			if(pemain.getGlobalBounds().intersects(obat6.getGlobalBounds())){
				dapat6=true;
				x6=5;
			}
			if(pemain.getGlobalBounds().intersects(obat7.getGlobalBounds())){
				dapat7=true;
				x7=5;
			}
			if(hitung-w<0){
				waktu.restart();
				ena="bab1xn1";
			}
			pemain.setRadius(ukuran+x1+x2+x3+x4+x5+x6+x7);
		}
		if(ena=="bab1xn1"){
			w=waktu.getElapsedTime().asSeconds();
			ahhh.draw(c1xn1);
			if(w>5){
				waktu.restart();
				ena="bab1xn2";
			}
		}
		if(ena=="bab1xn2"){
			w=waktu.getElapsedTime().asSeconds();
			ahhh.draw(c1xn2);
			if(w>5){
				waktu.restart();
				ena="bab1xn3";
			}
		}
		if(ena=="bab1xn3"){
			if(bgmgagaly==false){
				bgmseram.stop();bgmseramy=false;
				bgmserius.stop();bgmseriusy=false;
				bgmsedih.stop();bgmsedihy=false;
				bgmbiasa.stop();bgmbiasay=false;
				bgmgagal.play();bgmgagaly=true;
				bgmfinal.stop();bgmfinaly=false;
				bgmmain.stop();bgmmainy=false;
			}
			w=waktu.getElapsedTime().asSeconds();
			ahhh.draw(c1xn3);
			if(w>10){
				waktu.restart();
				ena="bab1xn4";
			}
		}
		if(ena=="bab1xn4"){
			w=waktu.getElapsedTime().asSeconds();
			ahhh.draw(c1xn4);
			if(w>15){
				waktu.restart();
				ena="bab1xn5";
			}
		}
		if(ena=="bab1xn5"){
			w=waktu.getElapsedTime().asSeconds();
			ahhh.draw(c1xn5);
			if(w>15){
				waktu.restart();
				ena="bab1xn6";
			}
		}
		if(ena=="bab1xn6"){
			w=waktu.getElapsedTime().asSeconds();
			ahhh.draw(c1xn6);
			if(w>15){
				waktu.restart();
				ena="bab1xn7";
			}
		}
		if(ena=="bab1xn7"){
			w=waktu.getElapsedTime().asSeconds();
			ahhh.draw(c1xn7);
			if(w>15){
				waktu.restart();
				ena="bab1xn8";
			}
		}
		if(ena=="bab1xn8"){
			w=waktu.getElapsedTime().asSeconds();
			ahhh.draw(c1xn8);
			if(w>15){
				waktu.restart();
				ena="bab1xn9";
			}
		}
		if(ena=="bab1xn9"){
			w=waktu.getElapsedTime().asSeconds();
			ahhh.draw(c1xn9);
			if(w>15){
				waktu.restart();
				ena="over";
			}
		}
		if(ena=="bab2n1"){
			if(bgmmainy==false){
				bgmseram.stop();bgmseramy=false;
				bgmserius.stop();bgmseriusy=false;
				bgmsedih.stop();bgmsedihy=false;
				bgmbiasa.stop();bgmbiasay=false;
				bgmgagal.stop();bgmgagaly=false;
				bgmfinal.stop();bgmfinaly=false;
				bgmmain.play();bgmmainy=true;
			}
			w=waktu.getElapsedTime().asSeconds();
			ahhh.draw(c2n1);
			if(w>5){
				waktu.restart();
				ena="bab2n2";
			}
		}
		if(ena=="bab2n2"){
			w=waktu.getElapsedTime().asSeconds();
			ahhh.draw(c2n2);
			if(w>5){
				waktu.restart();
				ena="bab2n3";
			}
		}
		if(ena=="bab2n3"){
			w=waktu.getElapsedTime().asSeconds();
			ahhh.draw(c2n3);
			if(w>5){
				waktu.restart();
				ena="bab2n4";
			}
		}
		if(ena=="bab2n4"){
			w=waktu.getElapsedTime().asSeconds();
			ahhh.draw(c2n4);
			if(w>5){
				waktu.restart();
				ena="bab2n5";
			}
		}
		if(ena=="bab2n5"){
			w=waktu.getElapsedTime().asSeconds();
			ahhh.draw(c2n5);
			if(w>5){
				waktu.restart();
				ena="bab2n6";
			}
		}
		if(ena=="bab2n6"){
			w=waktu.getElapsedTime().asSeconds();
			ahhh.draw(c2n6);
			if(w>5){
				waktu.restart();
				ena="bab2n7";
			}
		}
		if(ena=="bab2n7"){
			w=waktu.getElapsedTime().asSeconds();
			ahhh.draw(c2n7);
			if(w>5){
				waktu.restart();
				ena="bab2n8";
			}
		}
		if(ena=="bab2n8"){
			w=waktu.getElapsedTime().asSeconds();
			ahhh.draw(c2n8);
			if(w>5){
				waktu.restart();
				ena="bab2n9";
			}
		}
		if(ena=="bab2n9"){
			w=waktu.getElapsedTime().asSeconds();
			ahhh.draw(c2n9);
			if(w>5){
				waktu.restart();
				ena="menu";
			}
		}
		if(ena=="over"){
			ahhh.draw(over);
			if(bgmsedihy==false){
				bgmseram.stop();bgmseramy=false;
				bgmserius.stop();bgmseriusy=false;
				bgmsedih.play();bgmsedihy=true;
				bgmbiasa.stop();bgmbiasay=false;
				bgmgagal.stop();bgmgagaly=false;
				bgmfinal.stop();bgmfinaly=false;
				bgmmain.stop();bgmmainy=false;
			}
			if(Keyboard::isKeyPressed(Keyboard::Return)){
				waktu.restart();
				ena="menu";
			}
		}
		ahhh.display();
	}
}
